#fix: true               # default: false
parallel: true           # default: false
#format: progress        # default: Standard::Formatter
#ruby_version: 2.3.3     # default: RUBY_VERSION
#default_ignores: false  # default: true
#
ignore:
  - './**/*':
    - Style/RescueModifier
    - Style/StringLiterals
    - Style/StringLiteralsInInterpolation
    - Lint/AssignmentInCondition
    - Security/YAMLLoad
    - Layout/SpaceInsideHashLiteralBraces
    - Layout/ArgumentAlignment
    - Standard/SemanticBlocks
#  - 'db/schema.rb'
#  - 'vendor/**/*'
  - 'config/**/*'
  - 'spec/**/*':
    - Layout/EmptyLinesAroundBlockBody
#      - Layout/AlignHash
